apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ssl
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt    
spec:
  rules:
    - host: app1.frozenbread.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app1-nginx-clusterip-service
                port: 
                  number: 80
    - host: app2.frozenbread.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app2-nginx-clusterip-service
                port: 
                  number: 80
    - host: tekton.frozenbread.online
      http:
        paths:
          - path: /hooks
            pathType: Prefix
            backend:
              service:
                name: el-github-pr
                port: 
                  number: 8080                         
  tls:
  - hosts:
    - app1.frozenbread.online
    secretName: app1-frozenbread-secret           
  - hosts:
    - app2.frozenbread.online
    secretName: app2-frozenbread-secret
  - hosts:
    - tekton.frozenbread.online
    secretName: tekton-frozenbread-secret